-- local keymap = vim.keymap.set
-- local colors = require("catppuccin.palettes").get_palette('macchiato')
--
-- require('lspsaga').setup({
--   ui = {
--     colors = {
--       normal_bg = colors.base,
--       red = colors.red,
--       magenta = colors.flamingo,
--       orange = colors.peach,
--       yellow = colors.yellow,
--       green = colors.green,
--       cyan = colors.sky,
--       blue = colors.blue,
--       purple = colors.lavender,
--       white = '#d1d4cf',
--       black = colors.surface1
--     }
--   }
-- })
--
-- -- Lsp finder find the symbol definition implement reference
-- -- if there is no implement it will hide
-- -- when you use action in finder like open vsplit then you can
-- -- use <C-t> to jump back
-- keymap('n', 'gh', '<cmd>Lspsaga lsp_finder<CR>', { silent = true })
--
-- -- Code action
-- keymap({'n','v'}, '<leader>ca', '<cmd>Lspsaga code_action<CR>', { silent = true })
--
-- -- Rename
-- keymap('n', 'gn', '<cmd>Lspsaga rename<CR>', { silent = true })
--
-- -- Peek Definition
-- -- you can edit the definition file in this flaotwindow
-- -- also support open/vsplit/etc operation check definition_action_keys
-- -- support tagstack C-t jump back
-- keymap('n', 'gp', '<cmd>Lspsaga peek_definition<CR>', { silent = true })
--
-- -- Show line diagnostics
-- -- keymap('n', '<leader>cd', '<cmd>Lspsaga show_line_diagnostics<CR>', { silent = true })
-- keymap('n', 'gi', '<cmd>Lspsaga show_line_diagnostics<CR>', { silent = true })
--
-- -- Outline
-- keymap('n', '<leader>o', '<cmd>Lspsaga outline<CR>', { silent = true })
--
-- -- Go to definition
-- keymap('n', 'gd', '<cmd>Lspsaga goto_definition<CR>')
