# Config relating to the Lazygit UI
gui:
  # Nerd fonts version to use.
  # One of: '2' | '3' | empty string (default)
  # If empty, do not show icons.
  nerdFontsVersion: "3"

# Config relating to git
git:
  # Do not spawn a separate process when using GPG
  overrideGpg: true

# Don't display introductory popups upon opening Lazygit.
disableStartupPopups: false
